import { ApiProperty } from '@nestjs/swagger';

export enum SessionState {
  // Estados principais de navegação
  MAIN_MENU = 'MAIN_MENU',
  PROTOCOLO_MENU = 'PROTOCOLO_MENU',
  CONSULTAR_MATRICULA = 'CONSULTAR_MATRICULA',
  ASSISTENCIA_ESTUDANTIL = 'ASSISTENCIA_ESTUDANTIL',
  CURSOS_INGRESSO = 'CURSOS_INGRESSO',
  COMUNICACAO_SETORES = 'COMUNICACAO_SETORES',

  // Estados de processamento de consulta
  ESPERANDO_CPF_TELEFONE = 'ESPERANDO_CPF_TELEFONE',
  RESULTADO_CONSULTA = 'RESULTADO_CONSULTA',

  // Estados de protocolo
  TRANCAMENTO_REABERTURA = 'TRANCAMENTO_REABERTURA',
  EMITIR_DOCUMENTOS = 'EMITIR_DOCUMENTOS',
  JUSTIFICAR_FALTAS = 'JUSTIFICAR_FALTAS',
  ACOMPANHAR_PROCESSOS = 'ACOMPANHAR_PROCESSOS',
  CONSULTANDO_PROTOCOLO = 'CONSULTANDO_PROTOCOLO',
  REGISTRO_DOCUMENTO_PENDENTE = 'REGISTRO_DOCUMENTO_PENDENTE',

  // Estados para outras funcionalidades
  AGUARDANDO_RESPOSTA_SETOR = 'AGUARDANDO_RESPOSTA_SETOR',
  ATENDIMENTO_HUMANO = 'ATENDIMENTO_HUMANO',

  // Estados de sistema/controle
  ENCERRAMENTO = 'ENCERRAMENTO',
  EXPIRED = 'EXPIRED',

  // Novo estado para controle de fluxo de atendimento humano
  AGUARDANDO_DADOS_ATENDIMENTO = 'AGUARDANDO_DADOS_ATENDIMENTO',
}

// as classes UserData, AtendenteDados e Session foram removidas. Os dados agora são tratados diretamente via Prisma.
